name: kcmdemo
description: Kcm demo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  badges: ^3.1.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
